CREATE DATABASE IF NOT EXISTS `database`;
CREATE DATABASE IF NOT EXISTS `test`;


DROP USER IF EXISTS 'user'@'%';
CREATE USER 'user'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';