version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app:/app
    php:
        build:
            context: .
        volumes:
            - ./app:/app
        environment:
            - PHP_IDE_CONFIG=serverName=app
        container_name: technical_test_ec_php
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
        volumes:
            - mysqldata:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
volumes:
    mysqldata: {}
    mysqldata_test: {}