list_movies:
    path:           /api/{version}/movies
    controller:     App\Netflix\Movies\Infrastructure\EntryPoint\ListMovies
    methods:        GET
    requirements:
        version: v1

get_cost_of_rent:
    path:           /api/{version}/movies/cost
    controller:     App\Netflix\Renting\Infrastructure\EntryPoint\GetCostOfRent
    methods:        GET
    requirements:
        version: v1