services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Netflix\Shared\Domain\Bus\CommandBus:
    class: 'App\Netflix\Shared\Infrastructure\Bus\TacticianCommandBus'

  App\Netflix\Renting\Application\Command\Handler\RentMoviesHandler:
    tags:
      - { name: tactician.handler, command: App\Netflix\Renting\Application\Command\RentMovies, bus: default }