services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Netflix\Shared\Domain\Bus\QueryBus:
    class: 'App\Netflix\Shared\Infrastructure\Bus\TacticianQueryBus'

  App\Netflix\Movies\Application\Query\Handler\GetMoviesHandler:
    tags:
      - { name: tactician.handler, command: App\Netflix\Movies\Application\Query\GetMovies, bus: query }