doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            SharedEntities:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Netflix/Shared/Domain/Entity'
#                prefix: 'App\Netflix\Shared\Domain\Entity'
            SharedValueObjects:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Shared/Domain/ValueObject'
                prefix: 'App\Netflix\Shared\Domain\ValueObject'
            MoviesEntities:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Movies/Domain/Entity'
                prefix: 'App\Netflix\Movies\Domain\Entity'
            MoviesValueObjects:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Movies/Domain/ValueObject'
                prefix: 'App\Netflix\Movies\Domain\ValueObject'
            ClientsEntities:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Clients/Domain/Entity'
                prefix: 'App\Netflix\Clients\Domain\Entity'
            ClientsValueObjects:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Clients/Domain/ValueObject'
                prefix: 'App\Netflix\Clients\Domain\ValueObject'
            RentingEntities:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Renting/Domain/Entity'
                prefix: 'App\Netflix\Renting\Domain\Entity'
            RentingValueObjects:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Netflix/Renting/Domain/ValueObject'
                prefix: 'App\Netflix\Renting\Domain\ValueObject'
